### ISSUE TITLE
Recognize companies that use ReactiveUI

### ISSUE THREAD

**Issue by worldbeater** [reactiveui/website#282]
According to https://github.com/reactiveui/ReactiveUI/issues/979 large companies including GitHub, Atlassian, Amazon, Elastic and Slack are using ReactiveUI in their products. Worth placing logos of these companies to [ReactiveUI website main page](https://reactiveui.net) so new users see ReactiveUI is trusted by software giants. As discussed in Slack, we need to ask for permissions before doing that, to avoid licensing issues. So here is a list of companies to email:

- [ ] [Slack](https://github.com/reactiveui/ReactiveUI/issues/979#issuecomment-196735701) (used in Slack messenger for Windows Phone)
- [ ] [Atlassian](https://github.com/reactiveui/ReactiveUI/issues/979#issuecomment-324740903) (used in Source Tree)
- [ ] [Elastic](https://github.com/reactiveui/ReactiveUI/issues/979#issuecomment-271239842) (used in installers)
- [ ] [GitHub](https://visualstudio.github.com/) (used in their Visual Studio extension)
- [ ] [Amazon](https://github.com/reactiveui/ReactiveUI/issues/979#issuecomment-321149105) (used in Amazon Drive)

**Comment by glennawatson** [comment]
@shiftkey Paul Betts recommended reaching out to you about this one.

**Comment by shiftkey** [comment]
@glennawatson shoot me an email (my handle @ this website) and I'll figure out who to connect you with

**Comment by glennawatson** [comment]
Thanks - closing as stale. Open since 2019 without follow-through on the permissions emails. We can revisit if there's renewed appetite.
